/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 Real-Time Innovations, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

module rti {
    module holoscan {
        module example {
            struct Command {
                @key unsigned long target_id;
                unsigned long sample_index;
                string<64> instruction;
            };
        };
    };
};
